# Generated by Django 4.1.7 on 2023-02-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0002_alter_orden_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padron',
            name='monto_desembolso',
            field=models.IntegerField(),
        ),
    ]
